### ISSUE TITLE
Readme is incorrect

### ISSUE THREAD

**Issue by glennsarti** [poshbotio/PoshBot.Karma#2]
It appears this readme was copied from another module.  It should be updated with;

* Correct command list
* Remove the references to giphy

**Comment by glennsarti** [comment]
I'm happy to do this as part of hacktoberfest

**Comment by devblackops** [comment]
Oops. copypasta!

Yes, please do!

**Comment by devblackops** [comment]
Fixed in 997a3f190e450e51e488f7b0cb673acbc5108198
