### ISSUE TITLE
Karma <Object> returns Mentions & Reactions instead of reporting numbers

### ISSUE THREAD

**Issue by clee1107** [poshbotio/PoshBot.Karma#7]
When calling `!Karma Adobe` Poshbot replies to Mentions & reactions with success (checkmark) but nothing is posted to the channel command was executed/called from.

![image](https://user-images.githubusercontent.com/15145625/97026034-7caf5680-151e-11eb-8615-623b9a17bc96.png)

![image](https://user-images.githubusercontent.com/15145625/97026071-889b1880-151e-11eb-9373-4d718fb78fd5.png)

**Comment by devblackops** [comment]
Thanks for the issue @clee1107. I've fixed this in `2.1.0` which is now on the [PowerShell Gallery](https://www.powershellgallery.com/packages/PoshBot.Karma/2.1.0). 

Commit: https://github.com/poshbotio/PoshBot.Karma/commit/f14fe05677a9fcfde4820ef21e1b36bc94dea61a

To show the current karma for an item, you now need to run `!karma show <thing>`. This aligns better with the other subcommands.
